# Generated by Django 2.0.4 on 2018-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksauthors', '0003_auto_20180416_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book',
            new_name='books',
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='booksauthors.Book'),
        ),
    ]
